# This workflow packages and releases a new version
name: Release
on:
  push:
    tags: [ '[0-9].[0-9]+.[0-9]+' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Build+Check
        run: |
          ./gradlew --version
          ./gradlew -Pversion=$GITHUB_REF_NAME clean build
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: composeApp/build/reports/tests/
      - name: Package
        run: ./gradlew -Pversion=$GITHUB_REF_NAME packageReleaseUberJarForCurrentOS
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Survey Tool Jar
          path: composeApp/build/compose/jars/survey-tool-linux-x64-${{ github.ref_name }}-release.jar

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $GITHUB_REF_NAME --verify-tag --generate-notes -t $GITHUB_REF_NAME "composeApp/build/compose/jars/survey-tool-linux-x64-$GITHUB_REF_NAME-release.jar"

#      - name: Upload artifacts for Release
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload $GITHUB_REF_NAME composeApp/build/compose/jars/survey-tool-linux-x64-$GITHUB_REF_NAME-release.jar
