# This workflow packages and releases a new version
name: Release
on:
  push:
    tags: [ '[0-9].[0-9]+.[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Build+Check
        run: |
          ./gradlew --version
          ./gradlew -Pversion=$GITHUB_REF_NAME clean build
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: composeApp/build/reports/tests/
      - name: Package
        run: ./gradlew -Pversion=$GITHUB_REF_NAME packageReleaseUberJarForCurrentOS
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Survey Tool Jar
          path: composeApp/build/compose/jars/

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Create release..."
          response=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/{owner}/{repo}/releases \
            -f 'tag_name=$GITHUB_REF_NAME' \
            -f 'name=$GITHUB_REF_NAME' \
            -F "generate_release_notes=true")
          releaseId=$(echo $response | jq ".id")
          
          echo "Upload release artifact..."
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/{owner}/{repo}/releases/$releaseId/assets?name=com.zinkel.survey-linux-x64-$$GITHUB_REF_NAME-release.jar \
            -f '@composeApp/build/compose/jars/com.zinkel.survey-linux-x64-$$GITHUB_REF_NAME-release.jar'
